import type { CapacityHistoryDataset } from "./capacity-db";
import { BRAND_HEAD_HTML } from "./branding";
import { compactDuration } from "./duration";

const esc = (value: string) => value.replace(/[&<>"']/g, (char) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
}[char]!));

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function renderHistoryHtml(
  dataset: CapacityHistoryDataset,
  opts: { capacityHref?: string; spendHref?: string } = {},
): string {
  const generated = new Date(dataset.generatedAt).toISOString();
  const first = dataset.firstSampleAt ? new Date(dataset.firstSampleAt).toISOString() : "";
  const capacityHref = opts.capacityHref ?? "./";
  const spendHref = opts.spendHref ?? "spend.html";
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="dark">
${BRAND_HEAD_HTML}
<title>Spendwatch History</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fragment+Mono:ital@0;1&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{--bg:#0a0c0f;--surface:#11151a;--raised:#151a20;--line:#29313a;--ink:#f2f5f7;--muted:#89939d;--cyan:#68d5dc;--session:#68d5dc;--weekly:#e69a73;--credits:#8ea9ff}
*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink);font-family:"Manrope",sans-serif;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px),radial-gradient(800px 500px at 50% -180px,rgba(104,213,220,.13),transparent 70%);background-size:38px 38px,38px 38px,auto}
.shell{width:min(1120px,calc(100% - 36px));margin:0 auto;padding:30px 0 64px}.topbar{display:flex;align-items:center;gap:20px;padding-bottom:22px;border-bottom:1px solid var(--line)}.brand{font-family:"Fragment Mono",monospace;font-size:14px;letter-spacing:-.04em}.brand b{color:var(--cyan);font-weight:400}.nav{display:flex;gap:5px;margin-left:18px;padding:4px;background:#0d1014;border:1px solid #20262d;border-radius:9px}.nav a{padding:7px 11px;border-radius:6px;color:var(--muted);text-decoration:none;font-size:12px;font-weight:600}.nav a.active{color:var(--ink);background:var(--raised)}.refresh{margin-left:auto;appearance:none;border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:8px;padding:9px 12px;font:600 12px "Manrope",sans-serif;cursor:pointer}
.hero{display:grid;grid-template-columns:1fr auto;gap:24px;align-items:end;padding:30px 0 18px}.eyebrow{margin:0 0 6px;color:var(--cyan);font:11px "Fragment Mono",monospace;text-transform:uppercase;letter-spacing:.12em}.hero h1{font-size:clamp(32px,4.5vw,48px);line-height:.98;letter-spacing:-.055em;margin:0}.hero h1 span{color:#75808a}.hero p:last-child{color:var(--muted);font-size:12px;margin:11px 0 0}.archive{text-align:right}.archive strong{display:block;color:var(--cyan);font:20px "Fragment Mono",monospace}.archive span{color:var(--muted);font-size:10px}
.controls{position:sticky;top:0;z-index:5;display:flex;align-items:center;gap:8px;margin:0 0 12px;padding:10px;background:rgba(10,12,15,.92);border:1px solid var(--line);border-radius:11px;backdrop-filter:blur(12px)}.ranges{display:flex;gap:4px}.controls button,.controls input{appearance:none;border:1px solid #28313a;background:#0d1115;color:var(--muted);border-radius:6px;padding:7px 10px;font:10px "Fragment Mono",monospace}.controls button{cursor:pointer}.controls button.active{color:var(--ink);border-color:rgba(104,213,220,.45);background:rgba(104,213,220,.09)}.month-label{margin-left:auto;color:var(--muted);font:9px "Fragment Mono",monospace;text-transform:uppercase;letter-spacing:.09em}.controls input{color:var(--ink);color-scheme:dark}.clear-month{display:none}
.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.metric{padding:12px 14px;border:1px solid var(--line);border-radius:9px;background:rgba(17,21,26,.9)}.metric b{display:block;font:17px "Fragment Mono",monospace}.metric span{display:block;margin-top:3px;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}
.charts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{overflow:hidden;border:1px solid var(--line);border-radius:12px;background:linear-gradient(145deg,rgba(21,26,32,.98),rgba(15,19,24,.98));animation:enter .4s both}.card-head{display:flex;gap:10px;align-items:flex-start;padding:14px 15px 9px}.provider{color:var(--accent);font:9px "Fragment Mono",monospace;text-transform:uppercase;letter-spacing:.12em}.card h2{margin:3px 0 0;font-size:13px;letter-spacing:-.02em;overflow-wrap:anywhere}.current{margin-left:auto;text-align:right}.current strong{display:block;font:16px "Fragment Mono",monospace}.current span{color:var(--muted);font-size:8px}.legend{display:flex;gap:13px;padding:0 15px 8px;color:var(--muted);font:8px "Fragment Mono",monospace}.legend i{display:inline-block;width:7px;height:2px;margin:0 5px 2px 0;background:var(--tone)}.plot{position:relative;height:150px;border-top:1px solid rgba(41,49,58,.7);background:linear-gradient(180deg,rgba(255,255,255,.012),transparent)}.plot svg{width:100%;height:100%;display:block}.grid{stroke:#242b32;stroke-width:1}.line{fill:none;stroke:var(--tone);stroke-width:2;vector-effect:non-scaling-stroke}.dot{fill:var(--tone)}.empty{display:grid;place-items:center;height:100%;color:var(--muted);font:10px "Fragment Mono",monospace}.axis{display:flex;justify-content:space-between;padding:7px 15px 11px;color:#68727b;font:8px "Fragment Mono",monospace}.page-meta{display:flex;justify-content:space-between;gap:20px;margin-top:22px;color:#6e7881;font:10px "Fragment Mono",monospace}
@keyframes enter{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@media(max-width:760px){.shell{width:min(100% - 24px,1120px);padding-top:max(16px,env(safe-area-inset-top));padding-bottom:max(64px,env(safe-area-inset-bottom))}.topbar{display:grid;grid-template-columns:1fr auto;gap:12px 8px}.nav{grid-column:1/-1;grid-row:2;width:100%;margin:0;display:grid;grid-template-columns:repeat(3,1fr)}.nav a{display:grid;place-items:center;min-height:44px;padding:7px 5px;text-align:center}.refresh{min-height:44px}.hero{grid-template-columns:1fr}.archive{text-align:left}.controls{flex-wrap:wrap}.controls button,.controls input{min-height:44px}.ranges{flex-wrap:wrap}.month-label{margin-left:0}.charts{grid-template-columns:1fr}.summary{grid-template-columns:1fr 1fr}.summary .metric:last-child{grid-column:1/-1}.page-meta{flex-direction:column}.plot{height:135px}}@media(max-width:380px){.hero h1{font-size:30px}.controls{gap:6px;padding:8px}.controls button{padding-left:8px;padding-right:8px}.card-head{flex-wrap:wrap}.current{margin-left:0;text-align:left}.legend{flex-wrap:wrap}.summary{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}
</style></head><body><main class="shell">
<div class="topbar"><div class="brand"><b>spend</b>watch</div><nav class="nav"><a href="${esc(capacityHref)}">Capacity</a><a href="${esc(spendHref)}">Spend detail</a><a class="active" href="history.html">History</a></nav><button class="refresh" id="refresh">Refresh</button></div>
<section class="hero"><div><p class="eyebrow">Capacity archive</p><h1>See the pattern. <span>Plan the load.</span></h1><p>Every captured quota check, kept locally and condensed only for display.</p></div><div class="archive"><strong id="archive-age">Building archive</strong><span id="oldest-sample">oldest recoverable sample ${esc(first.slice(0,10) || "pending")}</span></div></section>
<section class="controls"><div class="ranges" id="ranges"><button data-range="1">24h</button><button data-range="7" class="active">7d</button><button data-range="30">30d</button><button data-range="90">90d</button><button data-range="all">All</button></div><label class="month-label" for="month">Past month</label><input id="month" type="month"><button class="clear-month" id="clear-month">Return to recent</button></section>
<section class="summary"><div class="metric"><b id="visible-samples">0</b><span>visible samples</span></div><div class="metric"><b id="stored-rows">${dataset.sampleCount.toLocaleString()}</b><span>stored rows</span></div><div class="metric"><b id="account-count">0</b><span>tracked accounts</span></div></section>
<section class="charts" id="charts"></section>
<div class="page-meta"><span>Recent history stays live in SQLite. Older verified archives remain restorable.</span><span id="generated" data-generated="${esc(generated)}">Generated ${esc(generated)}</span></div>
</main><script id="history-data" type="application/json">${safeJson(dataset)}</script><script>
const compactDuration=${compactDuration.toString()};
let data=JSON.parse(document.querySelector('#history-data').textContent);const tones={codex:'#68d5dc',claude:'#e69a73',copilot:'#8ea9ff',lokai:'#b8d96b'};let range='7',month='',refreshing=false;
const fmtDate=t=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(t));const fmtCompact=n=>new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(n);
const bounds=()=>{if(month){const [y,m]=month.split('-').map(Number),start=new Date(y,m-1,1).getTime(),end=new Date(y,m,1).getTime();return[start,end]}const end=Date.now();return[range==='all'?(data.firstSampleAt||0):end-Number(range)*86400000,end]};
const pathFor=(points,start,end,credits)=>{if(!points.length)return'';const values=points.map(p=>credits?p.value:100-p.value),max=credits?Math.max(1,...values)*1.08:100;return points.map((p,i)=>{const x=Math.max(0,Math.min(100,(p.at-start)/(end-start)*100)),y=95-Math.max(0,Math.min(1,(credits?p.value/max:(100-p.value)/100)))*90;return(i?'L':'M')+x.toFixed(2)+' '+y.toFixed(2)}).join(' ')};
function render(){const[start,end]=bounds(),grouped=new Map();let visible=0;for(const s of data.series){const points=s.points.filter(p=>p.at>=start&&p.at<end);visible+=points.length;if(!points.length)continue;const key=s.provider+'|'+s.account,item=grouped.get(key)||{provider:s.provider,account:s.account,series:[]};item.series.push({...s,points});grouped.set(key,item)}document.querySelector('#visible-samples').textContent=fmtCompact(visible);document.querySelector('#account-count').textContent=grouped.size;const charts=document.querySelector('#charts');if(!grouped.size){charts.innerHTML='<article class="card"><div class="plot"><div class="empty">No samples in this period</div></div></article>';return}charts.innerHTML=[...grouped.values()].map((item,index)=>{const quota=item.series.filter(s=>s.kind!=='credits'),credits=item.series.find(s=>s.kind==='credits'),latest=[...item.series].flatMap(s=>s.points.map(p=>({...p,kind:s.kind}))).sort((a,b)=>b.at-a.at)[0];const headline=latest?(latest.kind==='credits'?fmtCompact(latest.value)+' used':Math.round(100-latest.value)+'% left'):'No data';const lines=quota.map(s=>'<path class="line" style="--tone:'+(s.kind==='weekly'?'#e69a73':'#68d5dc')+'" d="'+pathFor(s.points,start,end,false)+'"/>').join('')+(credits?'<path class="line" style="--tone:#8ea9ff" d="'+pathFor(credits.points,start,end,true)+'"/>':'');const legend=item.series.map(s=>'<span style="--tone:'+(s.kind==='weekly'?'#e69a73':s.kind==='credits'?'#8ea9ff':'#68d5dc')+'"><i></i>'+s.kind+' · '+s.sampleCount.toLocaleString()+' raw</span>').join('');return'<article class="card" style="--accent:'+tones[item.provider]+';animation-delay:'+index*45+'ms"><header class="card-head"><div><span class="provider">'+item.provider+'</span><h2>'+escapeHtml(item.account)+'</h2></div><div class="current"><strong>'+headline+'</strong><span>'+fmtDate(latest.at)+'</span></div></header><div class="legend">'+legend+'</div><div class="plot"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path class="grid" d="M0 5H100M0 50H100M0 95H100"/>'+lines+'</svg></div><div class="axis"><span>'+fmtDate(start)+'</span><span>'+fmtDate(end)+'</span></div></article>'}).join('')}
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const updateMeta=()=>{const age=data.firstSampleAt?Math.max(1,Math.round((Date.now()-data.firstSampleAt)/86400000)):0;document.querySelector('#archive-age').textContent=age?age+' days retained':'Archive ready';document.querySelector('#oldest-sample').textContent='oldest recoverable sample '+(data.firstSampleAt?new Date(data.firstSampleAt).toISOString().slice(0,10):'pending');document.querySelector('#stored-rows').textContent=data.sampleCount.toLocaleString();const generated=document.querySelector('#generated'),ageMs=Math.max(0,Date.now()-Date.parse(generated.dataset.generated));generated.textContent=(ageMs<90000?'Updated just now':'Updated '+compactDuration(ageMs)+' ago')+' · values 60s'};
document.querySelectorAll('[data-range]').forEach(button=>button.addEventListener('click',()=>{range=button.dataset.range;month='';document.querySelector('#month').value='';document.querySelector('#clear-month').style.display='none';document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===button));render()}));document.querySelector('#month').addEventListener('change',event=>{month=event.target.value;document.querySelectorAll('[data-range]').forEach(x=>x.classList.remove('active'));document.querySelector('#clear-month').style.display=month?'block':'none';render()});document.querySelector('#clear-month').addEventListener('click',()=>{month='';document.querySelector('#month').value='';document.querySelector('[data-range="7"]').click()});
const refreshButton=document.querySelector('#refresh');const refreshValues=async()=>{if(refreshing)return;refreshing=true;refreshButton.setAttribute('aria-busy','true');refreshButton.textContent='Syncing';try{const url=new URL(location.href);url.hash='';url.searchParams.set('_',Date.now().toString());const response=await fetch(url,{cache:'no-store',headers:{Accept:'text/html'}});if(!response.ok)throw new Error('HTTP '+response.status);const next=new DOMParser().parseFromString(await response.text(),'text/html'),payload=next.querySelector('#history-data'),nextGenerated=next.querySelector('#generated');if(!payload)throw new Error('History payload missing');data=JSON.parse(payload.textContent);document.querySelector('#history-data').textContent=payload.textContent;if(nextGenerated)document.querySelector('#generated').dataset.generated=nextGenerated.dataset.generated||'';render();updateMeta();refreshButton.textContent='Updated';refreshButton.title='Values updated without reloading the page'}catch(error){refreshButton.textContent='Retry';refreshButton.title='Value refresh failed: '+String(error)}finally{refreshing=false;refreshButton.removeAttribute('aria-busy')}};
refreshButton.addEventListener('click',refreshValues);setInterval(refreshValues,60000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshValues()});updateMeta();render();
</script></body></html>`;
}
